version: "3"
services:
  api-database:
    image: mongo
    container_name: "api-database"
    ports:
      - 27017:27017
  api:
    image: person-reactive-api:0.0.1-SNAPSHOT

    ports:
      - 8081:8080
    links:
      - api-database
  ui:
    image: person-management-ui:0.0.1-SNAPSHOT
    
    ports:
      - 4200:4200
    